### ISSUE TITLE
Failed to read XML file

### ISSUE THREAD

**Issue by moongerim** [dic-iit/human-model-generator#1]
Hello!

I've installed the asked robotology by given manual. But during the installation, I did some steps differently. 
First, I created a folder 'build'
Then inside the build I made 
`cmake ..` and `ccmake ..`
But here I did not meet ROBOTOLOGY_ENABLE_MATLAB  line to ON it. 
After I made 
`make install` inside of iDynTree, not inside of the build folder.

The thing is that the folder was compiled. But when I run `computeHumanURDF.m` script on Matlab, it returns the next error:

`[Start] Computation of Subject_01 URDF model
        - Model with 66 DoFs (excluded hand DoFs)
        - Model without articulated hand
        - Subject mass: 85.00 [kg]
        - Subject height: 180.00 [m]
Error using xml_read (line 143)
Failed to read XML file
/home/robot/Documents/HRI/human-model-generator-master/human_23links/data/mvnx/Participant_541_Setup_A_Seq_3_Trial_1.xsens.mvnx

Error in extractDataFromMvnx (line 26)
mvnxData = xml_read(mvnxFilename);

Error in computeHumanURDF (line 111)
    suit = extractDataFromMvnx(bucket.mvnxFilename);`

Could you help with that?

**Comment by lrapetti** [comment]
Hi @moongerim, the main purpose of this tool is to generate a human model starting from a `.mvnx` file generated using the [Xsens](https://www.xsens.com/) human motion tracking suit. Is it what you want to achieve?

**Comment by moongerim** [comment]
> Hi @moongerim, the main purpose of this tool is to generate a human model starting from a `.mvnx` file generated using the [Xsens](https://www.xsens.com/) human motion tracking suit. Is it what you want to achieve?

Yes, exactly!

**Comment by claudia-lat** [comment]
@moongerim may be the error in the syntax of your file _Participant_541_Setup_A_Seq_3_Trial_1.xsens.mvnx_ ?
Try to play with the underscores (e.g., remove them) and to remove the dot before the word xsens.

**Comment by claudia-lat** [comment]
@moongerim did you fix the problem?

**Comment by moongerim** [comment]
hello Claudia,

no((
****************
*Best regards, *
*Aigerim Nurbayeva*
*Graduate student*
*Department of Robotics and Mechatronics*
*Nazarbayev  University*
*53 Kabanbay batyr Ave*
<https://maps.google.com/?q=53+Kabanbay+batyr+Ave.+Astana,+Republic+of+Kazakhstan&entry=gmail&source=g>
*Astana, Republic of Kazakhstan*
<https://maps.google.com/?q=53+Kabanbay+batyr+Ave.+Astana,+Republic+of+Kazakhstan&entry=gmail&source=g>

**Comment by claudia-lat** [comment]
Hi @moongerim would you like to send us your `.mvnx` so we can try to launch it and see if the error is there?

**Comment by moongerim** [comment]
Dear Claudia,
Sure!
 Participant_541_Setup_A_Seq_3_Trial_1.xsens.mvnx
<https://drive.google.com/file/d/1HP6PEOANkZiwQ9l-gUV1ekkx5REWBK6Z/view?usp=drive_web>
Best regards,
Aigerim Nurbayeva
Department of Robotics and Mechatronics
Nazarbayev  University

**Comment by claudia-lat** [comment]
Dear @moongerim, I was just able to create the model with your `.mvnx` file.
Some notes from my test:
- the syntax of the file we cited [here](https://github.com/dic-iit/human-model-generator/issues/1#issuecomment-649581357) doesn't change the final URDF model creation. You can use it!
- try to check if you have a folder structure like this
   <img width="825" alt="Screenshot 2020-10-05 at 10 48 58" src="https://user-images.githubusercontent.com/10923418/95062062-bb5ea780-06fc-11eb-9598-a8705dd9f9a0.png">
- your model will be automatically created in the Processed folder
- put [here](https://github.com/dic-iit/human-model-generator/blob/master/human_23links/computeHumanURDF.m#L110) the name of your `.mvnx`file
- I saw that [this line of the code](https://github.com/dic-iit/human-model-generator/blob/master/human_23links/src/extractDataFromMvnx.m#L26) took a while because your file is super big.

**Comment by claudia-lat** [comment]
Dear @moongerim we are supposing that you solved your problem. Is in this way? We'll soon proceed to close this issue.

**Comment by claudia-lat** [comment]
Closing this issue @moongerim. Let us know in the future if you experience new similar issue.
